# Generated by Django 3.2.9 on 2021-11-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('descripcion', models.TextField(max_length=250, verbose_name='descripcion')),
                ('marca', models.CharField(max_length=100, verbose_name='marca')),
                ('exist_actual', models.CharField(max_length=50, verbose_name='existencia')),
            ],
        ),
    ]
