# Generated by Django 3.2.9 on 2021-11-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen_productos', '0003_auto_20211129_0304'),
    ]

    operations = [
        migrations.DeleteModel(
            name='existecia',
        ),
        migrations.DeleteModel(
            name='familia',
        ),
        migrations.DeleteModel(
            name='marca',
        ),
        migrations.AddField(
            model_name='productos',
            name='exist_actual',
            field=models.CharField(choices=[('1', 'Sobre Stock'), ('2', 'en Stock'), ('3', 'bajo Stock'), ('4', 'sin stock'), ('5', 'descontinuado')], default='4', max_length=2),
        ),
        migrations.AddField(
            model_name='productos',
            name='marca',
            field=models.CharField(default='sin marca', max_length=250),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio_compra',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio_venta',
            field=models.IntegerField(default=0),
        ),
    ]
