# Generated by Django 3.2.9 on 2021-11-29 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen_productos', '0004_auto_20211129_0337'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='productos',
            new_name='Producto',
        ),
    ]
