# Generated by Django 3.2.9 on 2021-11-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen_productos', '0005_rename_productos_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(max_length=250, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='exist_actual',
            field=models.CharField(choices=[('1', 'Sobre Stock'), ('2', 'en Stock'), ('3', 'bajo Stock'), ('4', 'sin stock'), ('5', 'descontinuado')], default='4', max_length=50, verbose_name='existencia'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.CharField(default='sin marca', max_length=250, verbose_name='marca'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_compra',
            field=models.IntegerField(default=0, verbose_name='precio compra'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.IntegerField(default=0, verbose_name='precio venta'),
        ),
    ]
