# Generated by Django 3.2.9 on 2021-11-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen_productos', '0007_alter_producto_exist_actual'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='rut')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=150, verbose_name='apellido')),
                ('direccion', models.CharField(max_length=150, verbose_name='direccion')),
                ('telefono', models.CharField(max_length=9, verbose_name='telefono')),
                ('correo', models.EmailField(max_length=250, verbose_name='correo')),
            ],
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
