# Generated by Django 3.2.9 on 2021-11-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen_productos', '0008_auto_20211129_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='id',
            field=models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='rut'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.IntegerField(verbose_name='telefono'),
        ),
    ]
